"""add_email_to_collaborator

Revision ID: ca6116471ad7
Revises: baaefac971ad
Create Date: 2026-05-29 16:16:20.398559

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca6116471ad7"
down_revision: str | Sequence[str] | None = "baaefac971ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_collaborator",
        sa.Column("email", sa.String(length=100), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_collaborator", "email")
    # ### end Alembic commands ###
